(defparameter *small* 1)
(defparameter *big* 100)
(defun binary_search ()
  (ash (+ *small* *big*) -1))
(defun smaller()
  (setf *big* (1- (binary_search)))
  (binary_search))
(defun bigger()
  (setf *small* (1+ (binary_search)))
  (binary_search))
(defun start_over()
  (defparameter *small* 1)
  (defparameter *big* 100)
  (binary_search))
