(princ "A parameter i.e. not seen as data")
(princ "Hello World")
(princ "\"Hello World\", escaped style.")
'(This is seen as a data)
(expt 2 3)
(/ 55 34)
(/ 55.0 34.0)
(/ 55.0 34)
(/ 55 34.0)
(cons "A" "B")
(cons 'A 'B)
(cons 'A (cons 'B (cons 'C 'D)))
(cons 'A (cons 'B '(C D)))
